version: "3"

services:
  react-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    # ADD THIS SECTION:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - /react-app/node_modules
      - .:/react-app
  react-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    # ADD THIS SECTION:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CI=true
    volumes:
      - /react-app/node_modules
      - .:/react-app
    command: ["npm", "run", "test"]
